Update ReSukiSU.yml

diff --git a/.github/workflows/ReSukiSU.yml b/.github/workflows/ReSukiSU.yml
--- a/.github/workflows/ReSukiSU.yml
+++ b/.github/workflows/ReSukiSU.yml
@@ -674,10 +674,6 @@ jobs:
             cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch ./common/
             cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
             cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
-            cd ./common
-            echo "Applying SUSFS Patches"
-            patch -p1 < 50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch || true
-            echo "SUSFS Patches Application Complete"
           fi
 
           if [[ "${{ github.event.inputs.ZRAM }}" == 1* ]]; then
@@ -693,10 +689,10 @@ jobs:
           SUBLEVEL=$(grep '^SUBLEVEL *=' Makefile | head -n1 | cut -d= -f2 | tr -d ' ')
 
           if [ "$GKI_V" == "android13-5.15" ] && [ "$SUBLEVEL" -lt 123 ]; then
-            echo "Fixed some bugs caused by kernel versions 5.15.0~5.15.123 only supporting older versions of the C library"
+            echo "Fixed some Bugs Caused by Kernel Versions 5.15.0~5.15.123 only Supporting Older Versions of the C Library..."
             cp ../../Action-Build/patches/fix_5.15.legacy ./fix_5.15.legacy.patch
             patch -p1 < fix_5.15.legacy.patch
-            echo "Fix 5.15 patch complete"
+            echo "Fix 5.15 Patch Complete!"
           fi
 
           if [[ "${{ env.KV2 }}" == "66" && "${{ env.KV3 }}" -le 6630 && "${{ github.event.inputs.SUSFS_META }}" != "-1" ]]; then
@@ -717,18 +713,25 @@ jobs:
             fake_patched=0
             if [ "$GKI_V" = "android15-6.6" ]; then
               if ! grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
-                echo "Nr subpages not found, patching is underway"
+                echo "NR Subpages Not Found, Patches Underway..."
                 sed -i -e '/int ret = 0, copied = 0;/a \\tunsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;' -e '/int ret = 0, copied = 0;/a \\tpagemap_entry_t \*res = NULL;' ./fs/proc/task_mmu.c
                 fake_patched=1
               fi
             fi
             if [ "$GKI_V" = "android12-5.10" ] || [ "$GKI_V" = "android13-5.15" ] || [ "$GKI_V" = "android14-6.1" ]; then
               if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
-                echo "Applying 69 Hide Stuff Patches"
+                echo "Vma Pages Not Found, Patches Underway..."
+                fake_patched=1
+              else
+                echo "69 Other Hide Stuff Patches Underway..."
                 patch -p1 < 69_hide_stuff.patch || true
-                echo "69 Hide Stuff Patches Application Complete"
+                echo "69 Other Hide Stuff Patches Complete!"
               fi
             fi
+
+            echo "Applying SUSFS patch"
+            patch -p1 < 50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch || true
+            echo "SUSFS patch complete"
 
             # Revert
             if [ "$fake_patched" = 1 ]; then
