Update ReSukiSU.yml

diff --git a/.github/workflows/ReSukiSU.yml b/.github/workflows/ReSukiSU.yml
--- a/.github/workflows/ReSukiSU.yml
+++ b/.github/workflows/ReSukiSU.yml
@@ -629,107 +629,111 @@ jobs:
 
           echo "manager_branch=$BRANCH" >> "$GITHUB_OUTPUT"
           echo "manager_artifact=$ARTIFACT" >> "$GITHUB_OUTPUT"
-
-      - name: Add ReSukiSU or SukiSU-Ultra
+      
+      - name: Add KernelSU Forks
         run: |
+          # Go to Kernel Working Directory
           cd kernel_workspace/kernel_platform
-          MANAGER_BRANCH="${{ steps.manager.outputs.manager_branch }}"
-          KSU_META="${{ github.event.inputs.KSU_META }}"
-
-          # It must contain two delimiters (at least three fields)
-          if [[ "$(grep -o '/' <<< "$KSU_META" | wc -l)" -lt 2 ]]; then
-            echo "Error: The KSU meta parameter is missing the necessary separator '/'. format should be: branch name/custom identifier (optional)/commit hash (optional)"
-            exit 10
-          fi
-
-          # Parsing fields: Branch / Custom identifier / Manual hash
-          IFS='/' read -r BRANCH_NAME KSU_CUSTOM_TAG MANUAL_HASH <<< "$KSU_META"
-
-          echo "Branch name: $BRANCH_NAME"
-          [[ -n "$KSU_CUSTOM_TAG" ]] && echo "Custom version identification: $KSU_CUSTOM_TAG" || echo "Custom version identification: not enabled"
-          [[ -n "$MANUAL_HASH" ]] && echo "Manually specify hash: $MANUAL_HASH" || echo "Manually specify hash: not enabled"
-
-          if [[ ${{ github.event.inputs.KSU_META }} == "ReSukiSU-Main" ]]; then
-            curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/${MANAGER_BRANCH}/kernel/setup.sh" | bash -s "$BRANCH_NAME"
-            echo 'CONFIG_KSU_FULL_NAME_FORMAT="$KSU_VERSION-$KSU_CUSTOM_TAG"' >> ./common/arch/arm64/configs/gki_defconfig
+          if [[ ${{ github.event.inputs.MANAGER_SOURCE }} == "SukiSU-Ultra" ]]; then
+            echo "Configure SukiSU Ultra..."
+            curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/refs/heads/main/kernel/setup.sh" | bash -s builtin
             cd ./KernelSU
-           
-            if [[ -n "$KSU_CUSTOM_TAG" ]]; then
-            echo "KSU_CUSTOM_TAG=$KSU_CUSTOM_TAG" >> "$GITHUB_ENV"
-            fi
-            
-            if [[ -n "$MANUAL_HASH" ]]; then
-            git fetch origin "$BRANCH_NAME" --depth=50
-            git checkout "$MANUAL_HASH"
-            fi
-            
-            KSU_VERSION=$(expr $(git rev-list --count "$MANAGER_BRANCH" 2>/dev/null || echo 13000) + 30700)
-            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
-            echo "kSUVER=$KSU_VERSION" >> $GITHUB_OUTPUT
-          
-          else 
-            [[ ${{ github.event.inputs.KSU_META }} == "SukiSU-Ultra-Main" ]]; then
-            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/${MANAGER_BRANCH}/kernel/setup.sh" | bash -s "$BRANCH_NAME"
-            cd ./KernelSU
-            
-            # Manual Hash is Specified, Switch to Specified Hash/Commit
-            if [[ -n "$MANUAL_HASH" ]]; then
-               git fetch origin "$BRANCH_NAME" --depth=50
-               git checkout "$MANUAL_HASH"
-               SHORT_HASH=${MANUAL_HASH:0:8}
-            fi
-            
-            KSU_API_VERSION=$(curl -fsSL "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/$BRANCH_NAME/kernel/Kbuild" | \
-               grep -m1 "KSU_VERSION_API :=" | awk -F'= ' '{print $2}' | tr -d '[:space:]')
-              
-            if [[ -z "$KSU_API_VERSION" || "$(printf '%s\n' "$KSU_API_VERSION" "3.1.7" | sort -V | head -n1)" != "3.1.7" ]]; then
-               KSU_API_VERSION="3.1.7"
-            fi
-            
+            # Get a Short Hash of the Current Git Commit (8-bits)
+            GIT_COMMIT_HASH=$(git rev-parse --short=8 HEAD)
+            echo "Current Commit Hash: $GIT_COMMIT_HASH"
+            export KSU_VERSION=$KSU_VERSION
+            # Try up to 3 Times to Get the KernelSU API Version Number
+            for i in {1..3}; do
+              # Extract KSU API Version from Remote Kbuild
+              KSU_API_VERSION=$(curl -s "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/builtin/kernel/Kbuild" | 
+                # Look for the first line that contains the version definition
+                grep -m1 "KSU_VERSION_API :=" | 
+                # Extract the value after the equal sign
+                awk -F'= ' '{print $2}' | 
+                # Remove all whitespace
+                tr -d '[:space:]')
+              # If the version number is successfully obtained, the loop will be exited, otherwise wait 1 second and try again
+              [ -n "$KSU_API_VERSION" ] && break || sleep 1
+            done
+            # If the Acquisition Fails, Use the Default Version Number 3.1.7
+            [ -z "$KSU_API_VERSION"
+            [ -z "$KSU_API_VERSION" ] && KSU_API_VERSION="3.1.7"
+            # Store the API Version Number to a GitHub Environment Variable
             echo "KSU_API_VERSION=$KSU_API_VERSION" >> $GITHUB_ENV
-            GIT_HASH=$(git rev-parse --short HEAD)
-            echo "GIT_HASH=$GIT_HASH"
-            
-            # Assembly Version Number
-            if [[ -n "$MANUAL_HASH" ]]; then
-               USE_HASH="$SHORT_HASH"
-            else
-               USE_HASH="$GIT_HASH"
-            fi
-            
-            if [[ -z "$CUSTOM_TAG" ]]; then
-               VERSION_FULL="v$KSU_API_VERSION-$USE_HASH@$BRANCH_NAME"
-            else
-               VERSION_FULL="v$KSU_API_VERSION-$CUSTOM_TAG"
-            fi    
-
-            # Cleanup and Write KBuild Version Information
+            # Create Version Definition Template & Version Format Function: Use the Obtained Commit Hash and Fixed Suffix
+            # KSU Version API: API Version Definition
+            # KSU Version Full: Full Version Definition
+            VERSION_DEFINITIONS=$'define get_ksu_version_full\nv\\$1-'"$GIT_COMMIT_HASH"$'@Andrei\nendef\n\nKSU_VERSION_API := '"$KSU_API_VERSION"$'\nKSU_VERSION_FULL := v'"$KSU_API_VERSION"$'-'"$GIT_COMMIT_HASH"$'Andrei'
+            # Cleanup Old Version Definitions in the Kernel Kbuild
+            # Delete Version Functions
             sed -i '/define get_ksu_version_full/,/endef/d' kernel/Kbuild
+            # Delete API Version Definition
             sed -i '/KSU_VERSION_API :=/d' kernel/Kbuild
+            # Delete Full Version Definition
             sed -i '/KSU_VERSION_FULL :=/d' kernel/Kbuild
-
-            VERSION_DEFINITIONS=$(cat <<EOF
-            define get_ksu_version_full
-            $VERSION_FULL
-            endef
-
-            KSU_VERSION_API := $KSU_API_VERSION
-            KSU_VERSION_FULL := $VERSION_FULL
-            EOF
-            )
-
+            # Insert the New Version Definition After the Repo Owner Line
             awk -v def="$VERSION_DEFINITIONS" '
+              # When Repo Owner Line is Found, Insert the Version Definition and Set Markup
               /REPO_OWNER :=/ {print; print def; inserted=1; next}
+              # Print All Lines
               1
+              # If No Insertion Point is Found, Append it at the End of the Document
               END {if (!inserted) print def}
             ' kernel/Kbuild > kernel/Kbuild.tmp && mv kernel/Kbuild.tmp kernel/Kbuild
 
-              KSU_VERSION=$(expr $(git rev-list --count "$MANAGER_BRANCH" 2>/dev/null || echo 13000) + 37185)
-              echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            # Generate Custom Version Number (Based on Commit Count) to Use when it Fails 114514
+            KSU_VERSION=$(expr $(git rev-list --count main) + 37185 2>/dev/null || echo 114514)
+            # Store the Version Number to a GitHub Environment Variable
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
 
-              echo "::group::Eventually KBuild Preview of the Medium Version Information and some Debugging Results"
-              grep -A10 "REPO_OWNER" kernel/Kbuild
-              grep "KSU_VERSION_FULL" kernel/Kbuild
+            # Validate the Results of the Modifications
+            grep -A10 "REPO_OWNER" kernel/Kbuild  # Check the Contents After the Insertion Point
+            grep "KSU_VERSION_FULL" kernel/Kbuild # Confirm that the Version Definition Exists
+            echo "SukiSU-Ultra Version Number: v${KSU_API_VERSION}-${GIT_COMMIT_HASH}@Andrei"
+          elif [[ ${{ github.event.inputs.MANAGER_SOURCE }} == "ReSukiSU-Main" ]]; then
+            echo "Configure ReSukiSU..."
+            curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/refs/heads/main/kernel/setup.sh" | bash -s main
+            echo 'CONFIG_KSU_FULL_NAME_FORMAT="%TAG_NAME%-%COMMIT_SHA%@Andrei"' >> ./common/arch/arm64/configs/gki_defconfig
+            cd ./KernelSU
+            # Generate a Custom Version Number (Based on the Commit Count) to Use when it Fails 114514
+            KSU_VERSION=$(expr $(git rev-list --count main) + 30700 2>/dev/null || echo 114514)
+            # Store the Version Number to a GitHub Environment Variable
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
+          elif [[ ${{ github.event.inputs.MANAGER_SOURCE }} == "ksunext" ]]; then
+            echo "Configure KernelSU Next..."
+            curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/dev-susfs/kernel/setup.sh" | bash -s dev-susfs
+            cd KernelSU-Next
+            rm -rf .git
+            KSU_VERSION=$(expr $(curl -sI "https://api.github.com/repos/pershoot/KernelSU-Next/commits?sha=dev&per_page=1" | grep -i "link:" | sed -n 's/.*page=\([0-9]*\)>; rel="last".*/\1/p') "+" 30000)
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
+            sed -i "s/KSU_VERSION_FALLBACK := 1/KSU_VERSION_FALLBACK := $KSU_VERSION/g" kernel/Kbuild
+            KSU_GIT_TAG=$(curl -sL "https://api.github.com/repos/KernelSU-Next/KernelSU-Next/tags" | grep -o '"name": *"[^"]*"' | head -n 1 | sed 's/"name": "//;s/"//')
+            sed -i "s/KSU_VERSION_TAG_FALLBACK := v0.0.1/KSU_VERSION_TAG_FALLBACK := $KSU_GIT_TAG/g" kernel/Kbuild
+            # Add WildKSU Manager Support for KernelSU-Next
+            cd ../common/drivers/kernelsu
+            wget https://github.com/cctv18/oppo_oplus_realme_sm8750/raw/refs/heads/main/other_patch/apk_sign.patch
+            patch -p2 -N -F 3 < apk_sign.patch || true
+          elif [[ ${{ github.event.inputs.MANAGER_SOURCE }} == "mksu" ]]; then
+            echo "正在配置 MKSU (5ec1cff/KernelSU)..."
+            curl -LSs "https://raw.githubusercontent.com/5ec1cff/KernelSU/refs/heads/main/kernel/setup.sh" | bash -s main
+            cd ./KernelSU
+            KSU_VERSION=$(expr $(curl -sI "https://api.github.com/repos/5ec1cff/KernelSU/commits?sha=main&per_page=1" | grep -i "link:" | sed -n 's/.*page=\([0-9]*\)>; rel="last".*/\1/p') "+" 30000)
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
+            sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Kbuild
+          elif [[ ${{ github.event.inputs.MANAGER_SOURCE }} == "ksu" ]]; then
+            echo "正在配置原版 KernelSU (tiann/KernelSU)..."
+            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/refs/heads/main/kernel/setup.sh" | bash -s main
+            cd ./KernelSU
+            KSU_VERSION=$(expr $(curl -sI "https://api.github.com/repos/tiann/KernelSU/commits?sha=main&per_page=1" | grep -i "link:" | sed -n 's/.*page=\([0-9]*\)>; rel="last".*/\1/p') "+" 30000)
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
+            sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Kbuild
+          else
+            echo "No Built-in KernelSU Mode has been Selected to Skip KernelSU Configuration..."
           fi
 
       - name: Apply Patches ReSukiSU
