Update ReSukiSU.yml

diff --git a/.github/workflows/ReSukiSU.yml b/.github/workflows/ReSukiSU.yml
--- a/.github/workflows/ReSukiSU.yml
+++ b/.github/workflows/ReSukiSU.yml
@@ -653,75 +653,84 @@ jobs:
            curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/${MANAGER_BRANCH}/kernel/setup.sh" | bash -s "$BRANCH_NAME"
            echo 'CONFIG_KSU_FULL_NAME_FORMAT="$KSU_VERSION-$KSU_CUSTOM_TAG"' >> ./common/arch/arm64/configs/gki_defconfig
            cd ./KernelSU
+           
             if [[ -n "$KSU_CUSTOM_TAG" ]]; then
             echo "KSU_CUSTOM_TAG=$KSU_CUSTOM_TAG" >> "$GITHUB_ENV"
             fi
+            
             if [[ -n "$MANUAL_HASH" ]]; then
             git fetch origin "$BRANCH_NAME" --depth=50
             git checkout "$MANUAL_HASH"
             fi
-             KSU_VERSION=$(expr $(git rev-list --count "$MANAGER_BRANCH" 2>/dev/null || echo 13000) + 30700)
-             echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
-             echo "kSUVER=$KSU_VERSION" >> $GITHUB_OUTPUT
+            
+            KSU_VERSION=$(expr $(git rev-list --count "$MANAGER_BRANCH" 2>/dev/null || echo 13000) + 30700)
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            echo "kSUVER=$KSU_VERSION" >> $GITHUB_OUTPUT
           
           else [[ ${{ github.event.inputs.MANAGER_SOURCE }} == "SukiSU-Ultra-Main" ]]; then
-           curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/${MANAGER_BRANCH}/kernel/setup.sh" | bash -s "$BRANCH_NAME"
-           cd ./KernelSU
-           # If a Manual Hash is Specified, Switch to that Commit
-           if [[ -n "$MANUAL_HASH" ]]; then
-             git fetch origin "$BRANCH_NAME" --depth=50
-             git checkout "$MANUAL_HASH"
-             SHORT_HASH=${MANUAL_HASH:0:8}
+            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/${MANAGER_BRANCH}/kernel/setup.sh" | bash -s "$BRANCH_NAME"
+            cd ./KernelSU
+            
+            # Manual Hash is Specified, Switch to Specified Hash/Commit
+            if [[ -n "$MANUAL_HASH" ]]; then
+               git fetch origin "$BRANCH_NAME" --depth=50
+               git checkout "$MANUAL_HASH"
+               SHORT_HASH=${MANUAL_HASH:0:8}
+            fi
+            
+            KSU_API_VERSION=$(curl -fsSL "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/$BRANCH_NAME/kernel/Kbuild" | \
+               grep -m1 "KSU_VERSION_API :=" | awk -F'= ' '{print $2}' | tr -d '[:space:]')
+              
+            if [[ -z "$KSU_API_VERSION" || "$(printf '%s\n' "$KSU_API_VERSION" "3.1.7" | sort -V | head -n1)" != "3.1.7" ]]; then
+               KSU_API_VERSION="3.1.7"
+            fi
+            
+            echo "KSU_API_VERSION=$KSU_API_VERSION" >> $GITHUB_ENV
+            GIT_HASH=$(git rev-parse --short HEAD)
+            echo "GIT_HASH=$GIT_HASH"
+            
+            # Assembly Version Number
+            if [[ -n "$MANUAL_HASH" ]]; then
+               USE_HASH="$SHORT_HASH"
+            else
+               USE_HASH="$GIT_HASH"
+            fi
+            
+            if [[ -z "$CUSTOM_TAG" ]]; then
+               VERSION_FULL="v$KSU_API_VERSION-$USE_HASH@$BRANCH_NAME"
+            else
+               VERSION_FULL="v$KSU_API_VERSION-$CUSTOM_TAG"
+            fi    
+
+            # Cleanup and Write KBuild Version Information
+            sed -i '/define get_ksu_version_full/,/endef/d' kernel/Kbuild
+            sed -i '/KSU_VERSION_API :=/d' kernel/Kbuild
+            sed -i '/KSU_VERSION_FULL :=/d' kernel/Kbuild
+
+            VERSION_DEFINITIONS=$(cat <<EOF
+            define get_ksu_version_full
+            $VERSION_FULL
+            endef
+
+            KSU_VERSION_API := $KSU_API_VERSION
+            KSU_VERSION_FULL := $VERSION_FULL
+            EOF
+            )
+
+            awk -v def="$VERSION_DEFINITIONS" '
+              /REPO_OWNER :=/ {print; print def; inserted=1; next}
+              1
+              END {if (!inserted) print def}
+            ' kernel/Kbuild > kernel/Kbuild.tmp && mv kernel/Kbuild.tmp kernel/Kbuild
+
+              KSU_VERSION=$(expr $(git rev-list --count "$MANAGER_BRANCH" 2>/dev/null || echo 13000) + 37185)
+              echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+
+              echo "::group::Eventually KBuild Preview of the Medium Version Information and some Debugging Results"
+              grep -A10 "REPO_OWNER" kernel/Kbuild
+              grep "KSU_VERSION_FULL" kernel/Kbuild
+              echo "::endgroup::"
            fi
-           KSU_API_VERSION=$(curl -fsSL "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/$BRANCH_NAME/kernel/Kbuild" | \
-             grep -m1 "KSU_VERSION_API :=" | awk -F'= ' '{print $2}' | tr -d '[:space:]')
-           if [[ -z "$KSU_API_VERSION" || "$(printf '%s\n' "$KSU_API_VERSION" "3.1.7" | sort -V | head -n1)" != "3.1.7" ]]; then
-             KSU_API_VERSION="3.1.7"
-           fi
-           echo "KSU_API_VERSION=$KSU_API_VERSION" >> $GITHUB_ENV
-           GIT_HASH=$(git rev-parse --short HEAD)
-           echo "GIT_HASH=$GIT_HASH"
-           # Assembly Version Number
-           if [[ -n "$MANUAL_HASH" ]]; then
-             USE_HASH="$SHORT_HASH"
-           else
-             USE_HASH="$GIT_HASH"
-           fi
-           if [[ -z "$CUSTOM_TAG" ]]; then
-             VERSION_FULL="v$KSU_API_VERSION-$USE_HASH@$BRANCH_NAME"
-           else
-             VERSION_FULL="v$KSU_API_VERSION-$CUSTOM_TAG"
-           fi    
-
-           # Cleanup and Write KBuild Version Information
-           sed -i '/define get_ksu_version_full/,/endef/d' kernel/Kbuild
-           sed -i '/KSU_VERSION_API :=/d' kernel/Kbuild
-           sed -i '/KSU_VERSION_FULL :=/d' kernel/Kbuild
-
-           VERSION_DEFINITIONS=$(cat <<EOF
-             define get_ksu_version_full
-             $VERSION_FULL
-             endef
-
-             KSU_VERSION_API := $KSU_API_VERSION
-             KSU_VERSION_FULL := $VERSION_FULL
-           EOF
-           )
-
-           awk -v def="$VERSION_DEFINITIONS" '
-             /REPO_OWNER :=/ {print; print def; inserted=1; next}
-             1
-             END {if (!inserted) print def}
-           ' kernel/Kbuild > kernel/Kbuild.tmp && mv kernel/Kbuild.tmp kernel/Kbuild
-
-             KSU_VERSION=$(expr $(git rev-list --count "$MANAGER_BRANCH" 2>/dev/null || echo 13000) + 37185)
-             echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
-
-             echo "::group::Eventually KBuild Preview of the Medium Version Information and some Debugging Results"
-             grep -A10 "REPO_OWNER" kernel/Kbuild
-             grep "KSU_VERSION_FULL" kernel/Kbuild
-             echo "::endgroup::"
-          fi
 
       - name: Apply Patches ReSukiSU
         env:
