Update Test.yml

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -633,29 +633,16 @@ jobs:
       # ===============
       # Add Selected Root
       # ===============
-      - name: Add ReSukiSU Manager
-        if: ${{ github.event.inputs.KSU_META == 'ReSukiSU' }}
-        shell: bash
+      - name: Add Selected Root
+        id: manager
         run: |
-          cd kernel_workspace/kernel_platform          
-          curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/refs/heads/main/kernel/setup.sh" | bash -s main
-            echo 'CONFIG_KSU_FULL_NAME_FORMAT="%TAG_NAME%-Andrei"' >> ./common/arch/arm64/configs/gki_defconfig
+          # Go to Kernel Working Directory
+          cd kernel_workspace/kernel_platform
+          if [[ ${{ github.event.inputs.KSU_META }} == "SukiSU-Ultra" ]]; then
+            echo "Configure SukiSU Ultra..."
+            curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/refs/heads/main/kernel/setup.sh" | bash -s builtin
             cd ./KernelSU
-            # Generate a Custom Version Number (Based on the Commit Count) to Use when it Fails 114514
-            KSU_VERSION=$(expr $(git rev-list --count main) + 30700 2>/dev/null || echo 114514)
-            # Store the Version Number to a GitHub Environment Variable
-            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
-            echo "KSUVER=$KSU_VERSION" >> $GITHUB_OUTPUT
-            echo "::endgroup::"
-
-      - name: Add SukiSU Ultra
-        if: ${{ github.event.inputs.KSU_META == 'SukiSU-Ultra' }}
-        shell: bash
-        run: |
-          cd kernel_workspace/kernel_platform          
-          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/refs/heads/main/kernel/setup.sh" | bash -s main
-            cd ./KernelSU
-            # PULL SHORT HASH OF CURRENT GIT COMMIT
+            # Get a Short Hash of the Current Git Commit (8-bits)
             GIT_COMMIT_HASH=$(git rev-parse --short=8 HEAD)
             echo "Current Commit Hash: $GIT_COMMIT_HASH"
             export KSU_VERSION=$KSU_VERSION
@@ -663,7 +650,7 @@ jobs:
             # TRY UP TO 3 TIMES TO GET ROOT API VERSION NUMBER
             for i in {1..3}; do
               # EXTRACT KSU API Version FROM REMOTE KBUILD
-              KSU_API_VERSION=$(curl -s "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/Kbuild" | 
+              KSU_API_VERSION=$(curl -s "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/builtin/kernel/Kbuild" | 
                 # LOOK FOR FIRST LINE THAT CONTAINS VERSION DEFINITION
                 grep -m1 "KSU_VERSION_API :=" | 
                 # EXTRACT VALUE AFTER EQUAL SIGN
@@ -673,14 +660,87 @@ jobs:
               # IF VERSION NUMBER IS OBTAINED, LOOP WILL BE EXITED OTHERWISE WAIT FOR 1 SEC AND TRY AGAIN
               [ -n "$KSU_API_VERSION" ] && break || sleep 1
             done
-            # If ACQUISITION FAILS, USE DEFAULT VERSION NUMBER 3.1.7
+            # If the Acquisition Fails, Use the Default Version Number 3.1.7
             [ -z "$KSU_API_VERSION"
             [ -z "$KSU_API_VERSION" ] && KSU_API_VERSION="3.1.7"
-            
             # Store the API Version Number to a GitHub Environment Variable
-            echo "KSU_API_VERSION=$KSU_API_VERSION" >> $GITHUB_ENV 
+            echo "KSU_API_VERSION=$KSU_API_VERSION" >> $GITHUB_ENV
             # Create Version Definition Template & Version Format Function: Use the Obtained Commit Hash and Fixed Suffix
             # KSU_VERSION_API: API Version Definition
+            # KSU_VERSION_FULL: Full Version Definition
+            VERSION_DEFINITIONS=$'define get_ksu_version_full\nv\\$1-'"$GIT_COMMIT_HASH"$'@Andrei\nendef\n\nKSU_VERSION_API := '"$KSU_API_VERSION"$'\nKSU_VERSION_FULL := v'"$KSU_API_VERSION"$'-'"$GIT_COMMIT_HASH"$'Andrei'
+            # Cleanup the Old Version Definitions in the Kernel Kbuild
+            # Delete Version Functions
+            sed -i '/define get_ksu_version_full/,/endef/d' kernel/Kbuild
+            # Delete the API Version Definition
+            sed -i '/KSU_VERSION_API :=/d' kernel/Kbuild
+            # Delete the Full Version Definition
+            sed -i '/KSU_VERSION_FULL :=/d' kernel/Kbuild
+            # Insert the New Version Definition After the Repo Owner Line
+            awk -v def="$VERSION_DEFINITIONS" '
+              # When the Repo Owner Line is Found, Insert the Version Definition and Set the Markup
+              /REPO_OWNER :=/ {print; print def; inserted=1; next}
+              # Print All Lines
+              1
+              # If no Insertion Point is Found, Append it at the End of the Document
+              END {if (!inserted) print def}
+            ' kernel/Kbuild > kernel/Kbuild.tmp && mv kernel/Kbuild.tmp kernel/Kbuild
+
+            # Generate a Custom Version Number (Based on the Commit Count) to Use when it Fails 114514
+            KSU_VERSION=$(expr $(git rev-list --count main) + 37185 2>/dev/null || echo 114514)
+            # Store the Version Number to a GitHub Environment Variable
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
+
+            # Validate the Results of the Modifications
+            grep -A10 "REPO_OWNER" kernel/Kbuild  # Check the Contents After the Insertion Point
+            grep "KSU_VERSION_FULL" kernel/Kbuild # Confirm that the Version Definition Exists
+            echo "SukiSU-Ultra Version Number: v${KSU_API_VERSION}-${GIT_COMMIT_HASH}@Andrei"
+          elif [[ ${{ github.event.inputs.MANAGER_SOURCE }} == "ReSukiSU-Main" ]]; then
+            echo "Configure ReSukiSU..."
+            curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/refs/heads/main/kernel/setup.sh" | bash -s main
+            echo 'CONFIG_KSU_FULL_NAME_FORMAT="%TAG_NAME%-%COMMIT_SHA%@cctv18"' >> ./common/arch/arm64/configs/gki_defconfig
+            cd ./KernelSU
+            # Generate a Custom Version Number (Based on the Commit Count) to Use when it Fails 114514
+            KSU_VERSION=$(expr $(git rev-list --count main) + 30700 2>/dev/null || echo 114514)
+            # Store the Version Number to a GitHub Environment Variable
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
+          elif [[ ${{ github.event.inputs.KSU_META }} == "ksunext" ]]; then
+            echo "Configure KernelSU Next..."
+            curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/dev-susfs/kernel/setup.sh" | bash -s dev-susfs
+            cd KernelSU-Next
+            rm -rf .git
+            KSU_VERSION=$(expr $(curl -sI "https://api.github.com/repos/pershoot/KernelSU-Next/commits?sha=dev&per_page=1" | grep -i "link:" | sed -n 's/.*page=\([0-9]*\)>; rel="last".*/\1/p') "+" 30000)
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
+            sed -i "s/KSU_VERSION_FALLBACK := 1/KSU_VERSION_FALLBACK := $KSU_VERSION/g" kernel/Kbuild
+            KSU_GIT_TAG=$(curl -sL "https://api.github.com/repos/KernelSU-Next/KernelSU-Next/tags" | grep -o '"name": *"[^"]*"' | head -n 1 | sed 's/"name": "//;s/"//')
+            sed -i "s/KSU_VERSION_TAG_FALLBACK := v0.0.1/KSU_VERSION_TAG_FALLBACK := $KSU_GIT_TAG/g" kernel/Kbuild
+            # Add WildKSU Manager Support for KernelSU-Next
+            cd ../common/drivers/kernelsu
+            wget https://github.com/cctv18/oppo_oplus_realme_sm8750/raw/refs/heads/main/other_patch/apk_sign.patch
+            patch -p2 -N -F 3 < apk_sign.patch || true
+          elif [[ ${{ github.event.inputs.KSU_META }} == "mksu" ]]; then
+            echo "正在配置 MKSU (5ec1cff/KernelSU)..."
+            curl -LSs "https://raw.githubusercontent.com/5ec1cff/KernelSU/refs/heads/main/kernel/setup.sh" | bash -s main
+            cd ./KernelSU
+            KSU_VERSION=$(expr $(curl -sI "https://api.github.com/repos/5ec1cff/KernelSU/commits?sha=main&per_page=1" | grep -i "link:" | sed -n 's/.*page=\([0-9]*\)>; rel="last".*/\1/p') "+" 30000)
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
+            sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Kbuild
+          elif [[ ${{ github.event.inputs.KSU_META }} == "ksu" ]]; then
+            echo "正在配置原版 KernelSU (tiann/KernelSU)..."
+            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/refs/heads/main/kernel/setup.sh" | bash -s main
+            cd ./KernelSU
+            KSU_VERSION=$(expr $(curl -sI "https://api.github.com/repos/tiann/KernelSU/commits?sha=main&per_page=1" | grep -i "link:" | sed -n 's/.*page=\([0-9]*\)>; rel="last".*/\1/p') "+" 30000)
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
+            sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Kbuild
+          else
+            echo "No Built-in KernelSU Mode has been Selected to Skip KernelSU Configuration..."
+          fi
+      
             # KSU_VERSION_FULL: Full Version Definition
             VERSION_DEFINITIONS=$'define get_ksu_version_full\nv\\$1-'"$GIT_COMMIT_HASH"$'@Andrei\nendef\n\nKSU_VERSION_API := '"$KSU_API_VERSION"$'\nKSU_VERSION_FULL := v'"$KSU_API_VERSION"$'-'"$GIT_COMMIT_HASH"$'Andrei'
             # Cleanup the Old Version Definitions in the Kernel Kbuild
